webtalk_init -webtalk_dir C:/Users/Owner/Documents/HDL/VHDL/Lab-524/FSM-Digital-Lock-Design/Digital-Lock/Digital-Lock.sim/sim_1/behav/xsim/xsim.dir/fsm_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jan 28 16:34:36 2022" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2019.1 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2552052" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "55ea59b8-374f-48f7-a086-54e3c5295079" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "514212cb5a514440b4aec704172b71ea" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "34" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 9 3900X 12-Core Processor            " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3793 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "200 ns" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.19_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6348_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3893454577 -regid "" -xml C:/Users/Owner/Documents/HDL/VHDL/Lab-524/FSM-Digital-Lock-Design/Digital-Lock/Digital-Lock.sim/sim_1/behav/xsim/xsim.dir/fsm_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Owner/Documents/HDL/VHDL/Lab-524/FSM-Digital-Lock-Design/Digital-Lock/Digital-Lock.sim/sim_1/behav/xsim/xsim.dir/fsm_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Owner/Documents/HDL/VHDL/Lab-524/FSM-Digital-Lock-Design/Digital-Lock/Digital-Lock.sim/sim_1/behav/xsim/xsim.dir/fsm_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
